services:
  users:
    build: ./users
    container_name: users-api
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    networks:
      - kong-ee-net

  products:
    build: ./products
    container_name: products-api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - kong-ee-net

  kong-cp:
    image: "${GW_IMAGE:-kong/kong-gateway:3.11.0.2}" # Main Kong Gateway Control Plane (default to latest version)
    container_name: kong-cp
    restart: on-failure
    networks:
      - kong-ee-net
    environment:
      KONG_DATABASE: "off" # Use DB-less mode (declarative configuration)
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml # Path to declarative config file
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl # Admin API on HTTP + HTTPS
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002, 0.0.0.0:8445 ssl # Kong Manager on HTTP + HTTPS
      KONG_ADMIN_GUI_URL: http://${GW_HOST:-localhost}:8002 # URL for GUI links
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml:ro # Mount kong.yml from root
    ports:
      - "8000:8000" # Proxy HTTP
      - "8443:8443" # Proxy HTTPS
      - "8001:8001" # Admin API HTTP
      - "8444:8444" # Admin API HTTPS
      - "8002:8002" # Kong Manager HTTP
      - "8445:8445" # Kong Manager HTTPS

networks:
  kong-ee-net:
    driver: bridge
